### ISSUE TITLE
Stroke properties reset themself back to default

### ISSUE THREAD

**Issue by VGBijpuria** [VBproDev/Canvascript#12]
So, when you make a line in Canvascript, there are 2 properties you can change about them-

- Width
- Color

However, when you press the reset button, and then start manipulating these properties, your lines get resetted back to the default (color: Black, width: '1'). This anomaly does not immediately visibly, let me explain with an example.

You draw a blue colored line with width 2, it shows that. However, as soon as you draw another line, it resets to the default. Fix this 
behaviour.

**Comment by pappurohit99** [comment]
Hello, I am a first timer contributing to open source. Can I take a pass at this bug?

**Comment by VGBijpuria** [comment]
@pappurohit99 Yes sure, I have assigned you now and please check out the below commit.
