### ISSUE TITLE
Automated minification of JS/TS code

### ISSUE THREAD

**Issue by pappurohit99** [VBproDev/Canvascript#19]
Instead of manually minifying the code, consider using [webpack](https://www.npmjs.com/package/webpack#introduction) for minification of code. Linter support can be added to the build process

**Comment by VGBijpuria** [comment]
Can you raise a PR on it (today or tommorow as possible)?

**Comment by pappurohit99** [comment]
Will not be able to actively work on it, until the weekend :/

**Comment by VGBijpuria** [comment]
@pappurohit99 are you still wishing to work on this?

**Comment by pappurohit99** [comment]
Due to other commitments, I will have to take a break from this project. Apologies for the late intimation.
