### ISSUE TITLE
When user clicks on save, tell the user that the project is saved

### ISSUE THREAD

**Issue by VGBijpuria** [VBproDev/Canvascript#30]
This has been a big complaint that what does the save button do? well it saves the graphics drawn on the canvas but that fact is not too obvious. So to make it clearer, when the user clicks on save, make a green colored pop up window come out that tells the user 'design has been saved'. After 2 seconds, close the pop up.

Edit- To those who are confused why I made a commit that said this issue is solved, and then reopened this back again, That is because I mistakenly passed the solve of another issue and instead marked this as solved. This issue is still open.

**Comment by ThuanTheSecond** [comment]
Hello sir, I want to contribute to this issue, can you assign it for me?
