### ISSUE TITLE
If one sets the line width to 0, unexpected things happen (listed)

### ISSUE THREAD

**Issue by VGBijpuria** [VBproDev/Canvascript#8]
- First and foremost, the lines shouldn't _even be visible_, but they are with a width of 1.
- If you have it set to some other color, upon dragging it will retain that color, but after releasing the pointer it will revert to black.
- If you generate code, one observes  the ctx.strokeStyle = 0, this is very wrong behaviour and is probably a clue.

**To-Do**

- Fix the bugs listed above

**Comment by PartishtaP** [comment]
@VBproDev please assign me the issue.
I would like to work on it.

**Comment by PartishtaP** [comment]
@VBproDev assign me this, i would like to work on it.
